services:
  db:
    image: postgres:14
    container_name: odoo19-db
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo19-db-data:/var/lib/postgresql/data
    networks:
      - odoo19-net

  odoo:
    image: odoo:19.0
    container_name: odoo19-odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo19-web-data:/var/lib/odoo
    networks:
      - odoo19-net

volumes:
  odoo19-db-data:
  odoo19-web-data:

networks:
  odoo19-net:
